### ISSUE TITLE
Add runtime option to disable perf.

### ISSUE THREAD

**Issue by mrigger** [jku-ssw/benchmarks#10]
Currently, there is only a compile-time option to include or exclude perf. It would be desirable to either dynamically link a benchmark runner (where either the perf or default runner could be selected) or to introduce a run-time option to disable calls to perf, so runtimes that do not support it could still be executed.

**Comment by pointhi** [comment]
possible structure:

```json
{
  "harnesses": {
    "antirez-otree_test": {
      "benchmarks": ["otree.alloc_free"],
      "runtimes": {
        "valgrind-O3": {"stderr": "error output", "exit_code": 0}
      }
    }
  },
  "benchmarks": {
    "otree.alloc_free": {
      "valgrind-O3": {}
    }
  }
}
```
