### ISSUE TITLE
Add an option to exclude benchmarks

### ISSUE THREAD

**Issue by mrigger** [jku-ssw/benchmarks#17]
It would be desirable to add an option that allows excluding benchmarks by specifying their name, for example, if they otherwise get stuck in an endless loop during execution.

**Comment by pointhi** [comment]
we do not know the benchmark name until we execute, but we know the name of the harness.

There is a ```--filter-harness``` option where people can specify a whitelist/blacklist.

Whitelist: ```(bench1|bench2)```
Backlist: ```(?!(bench1|bench2))```
